spring:
  profiles:
    active: mailKey
  datasource:
    url: "jdbc:mariadb://localhost:3306/great"
    username: "greatManager"
    password: "great123!@#"


jwt:
  key: "v76yqlmjqowq45vmjn^*qor@#!kjvyuwqvr"